package com.weichuang.pojo;

import java.io.Serializable;

public class UmsUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_user.id
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_user.username
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_user.age
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_user.sex
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_user.name
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_user.money
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_user
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_user.id
     *
     * @return the value of ums_user.id
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_user.id
     *
     * @param id the value for ums_user.id
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_user.username
     *
     * @return the value of ums_user.username
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_user.username
     *
     * @param username the value for ums_user.username
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_user.age
     *
     * @return the value of ums_user.age
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_user.age
     *
     * @param age the value for ums_user.age
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_user.sex
     *
     * @return the value of ums_user.sex
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_user.sex
     *
     * @param sex the value for ums_user.sex
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_user.name
     *
     * @return the value of ums_user.name
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_user.name
     *
     * @param name the value for ums_user.name
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_user.money
     *
     * @return the value of ums_user.money
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_user.money
     *
     * @param money the value for ums_user.money
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", age=").append(age);
        sb.append(", sex=").append(sex);
        sb.append(", name=").append(name);
        sb.append(", money=").append(money);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}