package com.weichuang.mapper;

import com.weichuang.pojo.UmsUser;
import com.weichuang.pojo.UmsUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    long countByExample(UmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    int deleteByExample(UmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    int insert(UmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    int insertSelective(UmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    List<UmsUser> selectByExample(UmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    UmsUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    int updateByExampleSelective(@Param("record") UmsUser record, @Param("example") UmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    int updateByExample(@Param("record") UmsUser record, @Param("example") UmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    int updateByPrimaryKeySelective(UmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated Sun Jan 17 14:29:17 CST 2021
     */
    int updateByPrimaryKey(UmsUser record);
}